### ISSUE TITLE
npm i mashnet fails

### ISSUE THREAD

**Issue by stefan-overkamp** [sharedstreets/mashnet#9]
on win10

D:\projekte\mashnet>npm i mashnet
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> gl@4.5.0 install D:\projekte\mashnet\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install The specified module could not be found.
prebuild-install WARN install \\?\D:\projekte\mashnet\node_modules\gl\build\Release\webgl.node

D:\projekte\mashnet\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\OSGeo4W64\apps\Python37\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projekte\mashnet\node_modules\gl
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'D:\projekte\mashnet\package.json'
npm WARN mashnet No description
npm WARN mashnet No repository field.
npm WARN mashnet No README data
npm WARN mashnet No license field.

**Comment by the-matt-morris** [comment]
I know this is going way back, but have you found any workarounds, @stefan-overkamp ?

**Comment by stefan-overkamp** [comment]
No, have not tried any further.
